vendor: Cloudera, Inc.
name: Cloudera Cloud Factory
version: v1.0.0
website_url: https://cloudera.com
documentation_url: https://www.cloudera.com/services-and-support/professional-services.html
product_logo_url: https://www.cloudera.com/content/dam/www/marketing/images/logos/cloudera/cloudera-logo@2x.png
type: Installer
description: Cloudera Cloud Factory is a hybrid cloud management orchestration platform
contact_email_address : pdwivedi@cloudera.com