vendor: Loft Labs
name: vCluster Private Nodes
version: v0.30.0
website_url: https://www.vcluster.com/
repo_url: https://github.com/loft-sh/vcluster
documentation_url: https://www.vcluster.com/docs
product_logo_url: https://www.vcluster.com/docs/media/vCluster_horizontal-orange.svg
type: distribution
description: "Private nodes is a tenancy model for vCluster where, instead of sharing the host cluster's worker nodes, individual worker nodes are joined to a vCluster."
contact_email_address: cncf@loft.sh